/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author Student
 */
public class timedisp extends javax.swing.JFrame {

    /**
     * Creates new form timedisp
     */
    public timedisp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea01 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea02 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea03 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea04 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea06 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea00 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea34 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea14 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea15 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea40 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea41 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea44 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextArea25 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextArea26 = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTextArea46 = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextArea42 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTextArea43 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTextArea30 = new javax.swing.JTextArea();
        jScrollPane31 = new javax.swing.JScrollPane();
        jTextArea31 = new javax.swing.JTextArea();
        jScrollPane32 = new javax.swing.JScrollPane();
        jTextArea32 = new javax.swing.JTextArea();
        jScrollPane33 = new javax.swing.JScrollPane();
        jTextArea33 = new javax.swing.JTextArea();
        jScrollPane34 = new javax.swing.JScrollPane();
        jTextArea05 = new javax.swing.JTextArea();
        jScrollPane35 = new javax.swing.JScrollPane();
        jTextArea35 = new javax.swing.JTextArea();
        jScrollPane36 = new javax.swing.JScrollPane();
        jTextArea36 = new javax.swing.JTextArea();
        jScrollPane37 = new javax.swing.JScrollPane();
        jTextArea45 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14CSE1", "14CSE2", "15CSE1", "15CSE2", "16CSE1", "16CSE2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIME TABLE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea01.setEditable(false);
        jTextArea01.setColumns(4);
        jTextArea01.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea01.setRows(4);
        jScrollPane2.setViewportView(jTextArea01);

        jTextArea02.setEditable(false);
        jTextArea02.setColumns(4);
        jTextArea02.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea02.setRows(4);
        jScrollPane3.setViewportView(jTextArea02);

        jTextArea03.setEditable(false);
        jTextArea03.setColumns(4);
        jTextArea03.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea03.setRows(4);
        jScrollPane4.setViewportView(jTextArea03);

        jTextArea04.setEditable(false);
        jTextArea04.setColumns(4);
        jTextArea04.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea04.setRows(4);
        jScrollPane5.setViewportView(jTextArea04);

        jTextArea06.setEditable(false);
        jTextArea06.setColumns(4);
        jTextArea06.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea06.setRows(4);
        jScrollPane6.setViewportView(jTextArea06);

        jTextArea00.setEditable(false);
        jTextArea00.setColumns(4);
        jTextArea00.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea00.setRows(4);
        jScrollPane7.setViewportView(jTextArea00);

        jTextArea34.setEditable(false);
        jTextArea34.setColumns(4);
        jTextArea34.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea34.setRows(4);
        jScrollPane8.setViewportView(jTextArea34);

        jTextArea11.setEditable(false);
        jTextArea11.setColumns(4);
        jTextArea11.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea11.setRows(4);
        jScrollPane9.setViewportView(jTextArea11);

        jTextArea10.setEditable(false);
        jTextArea10.setColumns(4);
        jTextArea10.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea10.setRows(4);
        jScrollPane10.setViewportView(jTextArea10);

        jTextArea12.setEditable(false);
        jTextArea12.setColumns(4);
        jTextArea12.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea12.setRows(4);
        jScrollPane12.setViewportView(jTextArea12);

        jTextArea13.setEditable(false);
        jTextArea13.setColumns(4);
        jTextArea13.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea13.setRows(4);
        jScrollPane13.setViewportView(jTextArea13);

        jTextArea14.setEditable(false);
        jTextArea14.setColumns(4);
        jTextArea14.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea14.setRows(4);
        jScrollPane14.setViewportView(jTextArea14);

        jTextArea15.setEditable(false);
        jTextArea15.setColumns(4);
        jTextArea15.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea15.setRows(4);
        jScrollPane15.setViewportView(jTextArea15);

        jTextArea16.setEditable(false);
        jTextArea16.setColumns(4);
        jTextArea16.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea16.setRows(4);
        jScrollPane16.setViewportView(jTextArea16);

        jTextArea40.setEditable(false);
        jTextArea40.setColumns(4);
        jTextArea40.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea40.setRows(4);
        jScrollPane17.setViewportView(jTextArea40);

        jTextArea41.setEditable(false);
        jTextArea41.setColumns(4);
        jTextArea41.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea41.setRows(4);
        jScrollPane18.setViewportView(jTextArea41);

        jTextArea44.setEditable(false);
        jTextArea44.setColumns(4);
        jTextArea44.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea44.setRows(4);
        jScrollPane19.setViewportView(jTextArea44);

        jTextArea20.setEditable(false);
        jTextArea20.setColumns(4);
        jTextArea20.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea20.setRows(4);
        jScrollPane20.setViewportView(jTextArea20);

        jTextArea21.setEditable(false);
        jTextArea21.setColumns(4);
        jTextArea21.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea21.setRows(4);
        jScrollPane21.setViewportView(jTextArea21);

        jTextArea22.setEditable(false);
        jTextArea22.setColumns(4);
        jTextArea22.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea22.setRows(4);
        jScrollPane22.setViewportView(jTextArea22);

        jTextArea23.setEditable(false);
        jTextArea23.setColumns(4);
        jTextArea23.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea23.setRows(4);
        jScrollPane23.setViewportView(jTextArea23);

        jTextArea24.setEditable(false);
        jTextArea24.setColumns(4);
        jTextArea24.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea24.setRows(4);
        jScrollPane24.setViewportView(jTextArea24);

        jTextArea25.setEditable(false);
        jTextArea25.setColumns(4);
        jTextArea25.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea25.setRows(4);
        jScrollPane25.setViewportView(jTextArea25);

        jTextArea26.setEditable(false);
        jTextArea26.setColumns(4);
        jTextArea26.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea26.setRows(4);
        jScrollPane26.setViewportView(jTextArea26);

        jTextArea46.setEditable(false);
        jTextArea46.setColumns(4);
        jTextArea46.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea46.setRows(4);
        jScrollPane27.setViewportView(jTextArea46);

        jTextArea42.setEditable(false);
        jTextArea42.setColumns(4);
        jTextArea42.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea42.setRows(4);
        jScrollPane28.setViewportView(jTextArea42);

        jTextArea43.setEditable(false);
        jTextArea43.setColumns(4);
        jTextArea43.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea43.setRows(4);
        jScrollPane29.setViewportView(jTextArea43);

        jTextArea30.setEditable(false);
        jTextArea30.setColumns(4);
        jTextArea30.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea30.setRows(4);
        jScrollPane30.setViewportView(jTextArea30);

        jTextArea31.setEditable(false);
        jTextArea31.setColumns(4);
        jTextArea31.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea31.setRows(4);
        jScrollPane31.setViewportView(jTextArea31);

        jTextArea32.setEditable(false);
        jTextArea32.setColumns(4);
        jTextArea32.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea32.setRows(4);
        jScrollPane32.setViewportView(jTextArea32);

        jTextArea33.setEditable(false);
        jTextArea33.setColumns(4);
        jTextArea33.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea33.setRows(4);
        jScrollPane33.setViewportView(jTextArea33);

        jTextArea05.setEditable(false);
        jTextArea05.setColumns(4);
        jTextArea05.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea05.setRows(4);
        jScrollPane34.setViewportView(jTextArea05);

        jTextArea35.setEditable(false);
        jTextArea35.setColumns(4);
        jTextArea35.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea35.setRows(4);
        jScrollPane35.setViewportView(jTextArea35);

        jTextArea36.setEditable(false);
        jTextArea36.setColumns(4);
        jTextArea36.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea36.setRows(4);
        jScrollPane36.setViewportView(jTextArea36);

        jTextArea45.setEditable(false);
        jTextArea45.setColumns(4);
        jTextArea45.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea45.setRows(4);
        jScrollPane37.setViewportView(jTextArea45);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("DISPLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu3.setText("File");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Close");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar2.add(jMenu3);

        jMenu8.setText("Edit");

        jMenuItem5.setText("Add");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuItem7.setText("Update");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem7);

        jMenuBar2.add(jMenu8);

        jMenu5.setText("Display");

        jMenuItem2.setText("Teacher");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem4.setText("Course");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem6.setText("TTime");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jScrollPane20)
                            .addComponent(jScrollPane30, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jScrollPane17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane31)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jScrollPane21))
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jScrollPane12)
                            .addComponent(jScrollPane22)
                            .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(jScrollPane23)
                                    .addComponent(jScrollPane33))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(jScrollPane8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane35)
                                .addComponent(jScrollPane25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jScrollPane26)
                            .addComponent(jScrollPane36))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jScrollPane34))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(777, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane31, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jScrollPane34, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                            .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane35, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        switch(jComboBox1.getSelectedIndex()){
            case 0:
        }
       
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

     // TODO add your handling code here:
     System.exit(0);   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        AddC A=new AddC();
        A.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Update a=new Update();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String Day[]={"Mon","Tues","Wed","Thurs","Fri"};
        String Tname = null;
        String Time[]={"09:00:00","10:00:00","11:00:00","12:00:00","14:00:00","15:00:00","16:00:00"};
        javax.swing.JTextArea jTextArea[]={jTextArea00,jTextArea01,jTextArea02,jTextArea03,jTextArea04,jTextArea05,jTextArea06,jTextArea10,
            jTextArea11,jTextArea12,jTextArea13,jTextArea14,jTextArea15,jTextArea16,jTextArea20,jTextArea21,jTextArea22,jTextArea23,jTextArea24,jTextArea25,
            jTextArea26,jTextArea30,jTextArea31,jTextArea32,jTextArea33,jTextArea34,jTextArea35,jTextArea36,jTextArea40,jTextArea41,jTextArea42,jTextArea43,jTextArea44,
            jTextArea45,jTextArea46
        };
        switch(jComboBox1.getSelectedIndex()){
            case 0:Tname="14cse1";
            break;
            case 1:Tname="14cse2";
            break;
            case 2:Tname="15cse1";
            break;
            case 3:Tname="15cse2";
            break;
            case 4:Tname="16cse1";
            break;
            case 5:Tname="16cse2";
            break;
           
        }

        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/new_tt?zeroDateTimeBehavior=convertToNull","root", "");
            Statement stmt = (Statement) con.createStatement();
            int k=0;
            for(int i=0;i<Day.length;i++)
            {
                for(int j=0;j<Time.length;j++)
                {
                    System.out.println(i+" "+j);
                    String query="SELECT CID,TID,Room FROM " +Tname+" WHERE (Day='" +Day[i]+"' AND Time='" +Time[j]+"');";
                    ResultSet rs=stmt.executeQuery(query);

                    while(rs.next())
                    {
                        String CID = rs.getString("CID");
                        String TID = rs.getString("TID");
                        String Room = rs.getString("Room");

                        jTextArea[k].setText(CID+"\n"+TID+"\n"+Room);

                    }

                    k++;

                }

            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
           course a=new course();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        resche a=new resche();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
          
     
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timedisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timedisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timedisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timedisp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timedisp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private static javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private static javax.swing.JTextArea jTextArea00;
    private static javax.swing.JTextArea jTextArea01;
    private static javax.swing.JTextArea jTextArea02;
    private static javax.swing.JTextArea jTextArea03;
    private static javax.swing.JTextArea jTextArea04;
    private static javax.swing.JTextArea jTextArea05;
    private static javax.swing.JTextArea jTextArea06;
    private static javax.swing.JTextArea jTextArea10;
    private static javax.swing.JTextArea jTextArea11;
    private static javax.swing.JTextArea jTextArea12;
    private static javax.swing.JTextArea jTextArea13;
    private static javax.swing.JTextArea jTextArea14;
    private static javax.swing.JTextArea jTextArea15;
    private static javax.swing.JTextArea jTextArea16;
    private static javax.swing.JTextArea jTextArea20;
    private static javax.swing.JTextArea jTextArea21;
    private static javax.swing.JTextArea jTextArea22;
    private static javax.swing.JTextArea jTextArea23;
    private static javax.swing.JTextArea jTextArea24;
    private static javax.swing.JTextArea jTextArea25;
    private static javax.swing.JTextArea jTextArea26;
    private static javax.swing.JTextArea jTextArea30;
    private static javax.swing.JTextArea jTextArea31;
    private static javax.swing.JTextArea jTextArea32;
    private static javax.swing.JTextArea jTextArea33;
    private static javax.swing.JTextArea jTextArea34;
    private static javax.swing.JTextArea jTextArea35;
    private javax.swing.JTextArea jTextArea36;
    private static javax.swing.JTextArea jTextArea40;
    private static javax.swing.JTextArea jTextArea41;
    private static javax.swing.JTextArea jTextArea42;
    private static javax.swing.JTextArea jTextArea43;
    private static javax.swing.JTextArea jTextArea44;
    private static javax.swing.JTextArea jTextArea45;
    private static javax.swing.JTextArea jTextArea46;
    // End of variables declaration//GEN-END:variables
}
